### ISSUE TITLE
Test against stegcracker! verbose-output? `-a, --accessible` option?

### ISSUE THREAD

**Issue by maniac-en** [StegKraken/StegKraken#9]
When I came across StegKraken(or RustKraken), I wanted to test it out to know if it actually works like it's mentioned!

I used the following command for test:
```bash
steghide embed -cf test.jpg -ef works.txt -p "roxylove" -sf out.jpg
```
`roxylove` is on line `100028` in [rockyou.txt](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Leaked-Databases/rockyou.txt.tar.gz)

#### Output results

![Screenshot from 2020-10-03 22-56-06](https://user-images.githubusercontent.com/45049766/94997882-b77f3800-05cb-11eb-9fb3-7aa9d528d98f.png)

![Screenshot from 2020-10-03 22-44-34](https://user-images.githubusercontent.com/45049766/94997631-16dc4880-05ca-11eb-8cfe-48149b189ce5.png)

- [ ] Are the results above expected results or is it just slow for me? ( I said slow because I expected it to be very-fast like rustscan in-comparison to nmap, --no offense meant)
- [ ] Feature-request for verbose-output similar to stegcracker in place of `100000` or `200000` 
- [ ] what's the use of `-a, --accessible`?

Thankyou :peace_symbol:

**Comment by s1l3nt78** [comment]
Hey

It will be alot quicker.

It is still in development and being rewritten in c++

Once this is fully completed it will extrememly fast,


I'm about 2/3 of the way done with the conversion. Have just had a few things lately that have been throwing me curve balls. Such as my system crashing but back up and working on it

**Comment by maniac-en** [comment]
Cool, looking forward to it!

As per my original questions, are you adding verbose-mode?
What's the use `-a, --accessible` flag?

**Comment by s1l3nt78** [comment]
That is something that can be better answered by the projects creators.
@bee-san

**Comment by maniac-en** [comment]
@s1l3nt78 Just checking in on the conversion, when can we expect this amazing speed?
Also, @bee-san Can you please answer the above addressed questions?

**Comment by maniac-en** [comment]
https://web.archive.org/web/20210118215557/https://twitter.com/bee_sec_san/status/1351286503989796866
Closing the issue :(
